### ISSUE TITLE
install-debian.sh

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont#255]
Erreur d'installation

```
arsleust@arsleust-G74Sx /var/www/upont $ ./install-debian.sh 
Bienvenue sur le script d'installation de uPont
Ce script est destiné aux distributions Ubuntu-like. Un compte GitHub est nécessaire.
Adresse mail du compte GitHub : aceus02@gmail.com
Prénom Nom : Guillaume Desforges
Installation des dépendances...
Atteint http://repo.steampowered.com precise InRelease
Ign http://dl.google.com stable InRelease                                      
Ign http://archive.ubuntu.com trusty InRelease                                 
Ign http://archive.canonical.com trusty InRelease                              
Atteint http://ppa.launchpad.net trusty InRelease                              
Atteint http://dl.google.com stable Release.gpg                                
Atteint http://repo.steampowered.com precise/steam Sources                     
Atteint http://archive.ubuntu.com trusty-updates InRelease                     
Atteint http://archive.canonical.com trusty Release.gpg                        
Atteint http://ppa.launchpad.net trusty/main Sources                           
Atteint http://dl.google.com stable Release                                    
Atteint http://archive.ubuntu.com trusty Release.gpg                           
Atteint http://archive.canonical.com trusty Release                            
Atteint http://ppa.launchpad.net trusty/main amd64 Packages                    
Ign http://packages.linuxmint.com rebecca InRelease                            
Atteint http://repo.steampowered.com precise/steam amd64 Packages              
Ign http://extra.linuxmint.com rebecca InRelease                               
Atteint http://archive.ubuntu.com trusty-updates/main amd64 Packages           
Atteint http://ppa.launchpad.net trusty/main i386 Packages                     
Atteint http://archive.canonical.com trusty/partner amd64 Packages             
Atteint http://dl.google.com stable/main amd64 Packages                        
Atteint http://security.ubuntu.com trusty-security InRelease                   
Atteint http://archive.ubuntu.com trusty-updates/restricted amd64 Packages     
Atteint http://ppa.launchpad.net trusty/main Translation-en                    
Atteint http://archive.canonical.com trusty/partner i386 Packages              
Atteint https://deb.nodesource.com trusty InRelease                            
Atteint http://repo.steampowered.com precise/steam i386 Packages               
Atteint http://archive.ubuntu.com trusty-updates/universe amd64 Packages       
Atteint http://archive.canonical.com trusty/partner Translation-en             
Atteint https://deb.nodesource.com trusty/main Sources                         
Atteint http://packages.linuxmint.com rebecca Release.gpg                      
Atteint http://extra.linuxmint.com rebecca Release.gpg                         
Atteint http://security.ubuntu.com trusty-security/main amd64 Packages         
Atteint https://deb.nodesource.com trusty/main amd64 Packages                  
Atteint http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages     
Atteint http://archive.ubuntu.com trusty-updates/main i386 Packages            
Atteint https://deb.nodesource.com trusty/main i386 Packages                   
Atteint http://archive.ubuntu.com trusty-updates/restricted i386 Packages      
Atteint http://security.ubuntu.com trusty-security/restricted amd64 Packages   
Atteint http://archive.ubuntu.com trusty-updates/universe i386 Packages        
Atteint http://packages.linuxmint.com rebecca Release                          
Atteint http://extra.linuxmint.com rebecca Release                             
Atteint http://security.ubuntu.com trusty-security/universe amd64 Packages     
Atteint http://archive.ubuntu.com trusty-updates/multiverse i386 Packages      
Atteint http://archive.ubuntu.com trusty-updates/main Translation-en           
Réception de : 1 https://deb.nodesource.com trusty/main Translation-fr_FR      
Atteint http://security.ubuntu.com trusty-security/multiverse amd64 Packages   
Atteint http://archive.ubuntu.com trusty-updates/multiverse Translation-en     
Atteint http://archive.ubuntu.com trusty-updates/restricted Translation-en     
Atteint http://security.ubuntu.com trusty-security/main i386 Packages          
Atteint http://archive.ubuntu.com trusty-updates/universe Translation-en       
Atteint http://packages.linuxmint.com rebecca/main amd64 Packages              
Atteint http://extra.linuxmint.com rebecca/main amd64 Packages                 
Atteint http://archive.ubuntu.com trusty Release                               
Atteint http://archive.ubuntu.com trusty/main amd64 Packages                   
Ign http://dl.google.com stable/main Translation-fr_FR                         
Atteint http://security.ubuntu.com trusty-security/restricted i386 Packages    
Ign http://dl.google.com stable/main Translation-fr                            
Atteint http://archive.ubuntu.com trusty/restricted amd64 Packages             
Ign http://dl.google.com stable/main Translation-en                            
Atteint http://security.ubuntu.com trusty-security/universe i386 Packages      
Atteint http://packages.linuxmint.com rebecca/upstream amd64 Packages          
Atteint http://extra.linuxmint.com rebecca/main i386 Packages                  
Atteint http://archive.ubuntu.com trusty/universe amd64 Packages               
Atteint http://security.ubuntu.com trusty-security/multiverse i386 Packages    
Atteint http://archive.ubuntu.com trusty/multiverse amd64 Packages             
Atteint http://archive.ubuntu.com trusty/main i386 Packages                    
Atteint http://security.ubuntu.com trusty-security/main Translation-en         
Atteint http://archive.ubuntu.com trusty/restricted i386 Packages              
Atteint http://packages.linuxmint.com rebecca/import amd64 Packages            
Atteint http://archive.ubuntu.com trusty/universe i386 Packages                
Atteint http://archive.ubuntu.com trusty/multiverse i386 Packages              
Atteint http://security.ubuntu.com trusty-security/multiverse Translation-en   
Atteint http://archive.ubuntu.com trusty/main Translation-fr                   
Atteint http://security.ubuntu.com trusty-security/restricted Translation-en   
Atteint http://archive.ubuntu.com trusty/main Translation-en                   
Atteint http://packages.linuxmint.com rebecca/main i386 Packages               
Atteint http://security.ubuntu.com trusty-security/universe Translation-en     
Atteint http://archive.ubuntu.com trusty/multiverse Translation-fr             
Atteint http://archive.ubuntu.com trusty/multiverse Translation-en             
Atteint http://archive.ubuntu.com trusty/restricted Translation-fr             
Atteint http://packages.linuxmint.com rebecca/upstream i386 Packages           
Atteint http://archive.ubuntu.com trusty/restricted Translation-en             
Atteint http://archive.ubuntu.com trusty/universe Translation-fr               
Atteint http://archive.ubuntu.com trusty/universe Translation-en               
Atteint http://packages.linuxmint.com rebecca/import i386 Packages             
Ign https://deb.nodesource.com trusty/main Translation-fr_FR                   
Ign https://deb.nodesource.com trusty/main Translation-fr                      
Ign https://deb.nodesource.com trusty/main Translation-en                      
Ign http://archive.ubuntu.com trusty/main Translation-fr_FR                    
Ign http://archive.ubuntu.com trusty/multiverse Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/restricted Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/universe Translation-fr_FR                
Ign http://extra.linuxmint.com rebecca/main Translation-fr_FR                  
Ign http://extra.linuxmint.com rebecca/main Translation-fr                     
Ign http://extra.linuxmint.com rebecca/main Translation-en                     
Ign http://repo.steampowered.com precise/steam Translation-fr_FR               
Ign http://repo.steampowered.com precise/steam Translation-fr                  
Ign http://repo.steampowered.com precise/steam Translation-en                  
Ign http://packages.linuxmint.com rebecca/import Translation-fr_FR             
Ign http://packages.linuxmint.com rebecca/import Translation-fr                
Ign http://packages.linuxmint.com rebecca/import Translation-en                
Ign http://packages.linuxmint.com rebecca/main Translation-fr_FR               
Ign http://packages.linuxmint.com rebecca/main Translation-fr                  
Ign http://packages.linuxmint.com rebecca/main Translation-en                  
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr_FR           
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr              
Ign http://packages.linuxmint.com rebecca/upstream Translation-en              
Lecture des listes de paquets... Fait                                          
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
expect est déjà la plus récente version disponible.
make est déjà la plus récente version disponible.
nano est déjà la plus récente version disponible.
zip est déjà la plus récente version disponible.
netcat est déjà la plus récente version disponible.
sl est déjà la plus récente version disponible.
tree est déjà la plus récente version disponible.
curl est déjà la plus récente version disponible.
git est déjà la plus récente version disponible.
unzip est déjà la plus récente version disponible.
vim est déjà la plus récente version disponible.
traceroute est déjà la plus récente version disponible.
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  ax25-node gyp libax25 libc-ares-dev libc-ares2 libjs-node-uuid libssl-dev
  libv8-3.14-dev libv8-3.14.5 node-abbrev node-ansi node-archy node-async
  node-block-stream node-combined-stream node-cookie-jar node-delayed-stream
  node-forever-agent node-form-data node-fstream node-fstream-ignore
  node-github-url-from-git node-glob node-graceful-fs node-gyp node-inherits
  node-ini node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs
  node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-which openbsd-inetd zlib1g-dev
Veuillez utiliser « apt-get autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 771 non mis à jour.
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet php-cli
E: Impossible de trouver le paquet php-fpm
E: Impossible de trouver le paquet php-curl
E: Impossible de trouver le paquet php-gd
E: Impossible de trouver le paquet php-imap
E: Impossible de trouver le paquet php-intl
E: Impossible de trouver le paquet php-mcrypt
E: Impossible de trouver le paquet php-mysql
Attribution des permissions...
usermod: Permission denied.
usermod : impossible de verrouiller /etc/passwd ; veuillez réessayer plus tard.
Configuration de git...
Création d'une base de données...
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
cp: impossible de créer le fichier standard «/etc/php/7.0/fpm/pool.d/www.conf-debian»: Aucun fichier ou dossier de ce type
mkdir: impossible de créer le répertoire «/etc/php/7.0/conf.d»: Aucun fichier ou dossier de ce type
cp: impossible de créer le fichier standard «/etc/php/7.0/conf.d/global.ini»: Aucun fichier ou dossier de ce type
cp: impossible de créer le fichier standard «/etc/nginx/conf.d/php-fpm.conf»: Aucun fichier ou dossier de ce type
php-fpm: unrecognized service
Installation de Composer...
sudo: php: command not found
mv: impossible d'évaluer «/usr/local/bin/composer.phar»: Aucun fichier ou dossier de ce type
mkdir: impossible de créer le répertoire «/home/arsleust/.composer»: Le fichier existe
chmod: impossible d'accéder à «/home/arsleust/.composer/cache»: Aucun fichier ou dossier de ce type
Installation de Phpdoc...
sudo: php: command not found
mv: impossible d'évaluer «/usr/local/bin/phpDocumentor.phar»: Aucun fichier ou dossier de ce type
Configuration de Nginx...
cp: impossible de créer le fichier standard «/etc/nginx/sites-available/dev-upont.enpc.fr.conf»: Aucun fichier ou dossier de ce type
ln: impossible de créer le lien symbolique «/etc/nginx/sites-enabled/dev-upont.enpc.fr.conf»: Aucun fichier ou dossier de ce type
nginx: unrecognized service
Configuration du proxy...
\e[31mPas de proxy configuré.\e[0m
Installation de nodejs, bower et gulp...

## Installing the NodeSource Node.js v4.x LTS Argon repo...


## Populating apt-get cache...

+ apt-get update
Atteint http://repo.steampowered.com precise InRelease
Atteint http://security.ubuntu.com trusty-security InRelease                   
Ign http://archive.canonical.com trusty InRelease                              
Ign http://archive.ubuntu.com trusty InRelease                                 
Atteint http://ppa.launchpad.net trusty InRelease                              
Ign http://dl.google.com stable InRelease                                      
Atteint http://archive.ubuntu.com trusty-updates InRelease                     
Atteint http://repo.steampowered.com precise/steam Sources                     
Atteint http://archive.canonical.com trusty Release.gpg                        
Atteint http://dl.google.com stable Release.gpg                                
Atteint http://security.ubuntu.com trusty-security/main amd64 Packages         
Atteint http://ppa.launchpad.net trusty/main Sources                           
Atteint http://archive.ubuntu.com trusty Release.gpg                           
Atteint http://archive.canonical.com trusty Release                            
Atteint http://dl.google.com stable Release                                    
Atteint http://security.ubuntu.com trusty-security/restricted amd64 Packages   
Atteint http://archive.ubuntu.com trusty-updates/main amd64 Packages           
Atteint http://ppa.launchpad.net trusty/main amd64 Packages                    
Atteint http://repo.steampowered.com precise/steam amd64 Packages              
Atteint http://archive.canonical.com trusty/partner amd64 Packages             
Ign http://packages.linuxmint.com rebecca InRelease                            
Ign http://extra.linuxmint.com rebecca InRelease                               
Atteint http://security.ubuntu.com trusty-security/universe amd64 Packages     
Atteint http://archive.ubuntu.com trusty-updates/restricted amd64 Packages     
Atteint http://ppa.launchpad.net trusty/main i386 Packages                     
Atteint http://dl.google.com stable/main amd64 Packages                        
Atteint http://archive.canonical.com trusty/partner i386 Packages              
Atteint http://repo.steampowered.com precise/steam i386 Packages               
Atteint https://deb.nodesource.com trusty InRelease                            
Atteint http://security.ubuntu.com trusty-security/multiverse amd64 Packages   
Atteint http://archive.ubuntu.com trusty-updates/universe amd64 Packages       
Atteint http://ppa.launchpad.net trusty/main Translation-en                    
Atteint http://archive.canonical.com trusty/partner Translation-en             
Atteint https://deb.nodesource.com trusty/main Sources                         
Atteint http://security.ubuntu.com trusty-security/main i386 Packages          
Atteint http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages     
Atteint http://packages.linuxmint.com rebecca Release.gpg                      
Atteint http://extra.linuxmint.com rebecca Release.gpg                         
Atteint https://deb.nodesource.com trusty/main amd64 Packages                  
Atteint http://security.ubuntu.com trusty-security/restricted i386 Packages    
Atteint http://archive.ubuntu.com trusty-updates/main i386 Packages            
Atteint https://deb.nodesource.com trusty/main i386 Packages                   
Atteint http://archive.ubuntu.com trusty-updates/restricted i386 Packages      
Atteint http://security.ubuntu.com trusty-security/universe i386 Packages      
Réception de : 1 https://deb.nodesource.com trusty/main Translation-fr_FR      
Atteint http://security.ubuntu.com trusty-security/multiverse i386 Packages    
Atteint http://archive.ubuntu.com trusty-updates/universe i386 Packages        
Atteint http://security.ubuntu.com trusty-security/main Translation-en         
Atteint http://archive.ubuntu.com trusty-updates/multiverse i386 Packages      
Atteint http://security.ubuntu.com trusty-security/multiverse Translation-en   
Atteint http://archive.ubuntu.com trusty-updates/main Translation-en           
Atteint http://packages.linuxmint.com rebecca Release                          
Atteint http://extra.linuxmint.com rebecca Release                             
Atteint http://security.ubuntu.com trusty-security/restricted Translation-en   
Atteint http://archive.ubuntu.com trusty-updates/multiverse Translation-en     
Atteint http://archive.ubuntu.com trusty-updates/restricted Translation-en     
Atteint http://security.ubuntu.com trusty-security/universe Translation-en     
Atteint http://archive.ubuntu.com trusty-updates/universe Translation-en       
Atteint http://archive.ubuntu.com trusty Release                               
Atteint http://extra.linuxmint.com rebecca/main amd64 Packages                 
Atteint http://archive.ubuntu.com trusty/main amd64 Packages                   
Atteint http://packages.linuxmint.com rebecca/main amd64 Packages              
Ign http://dl.google.com stable/main Translation-fr_FR                         
Atteint http://archive.ubuntu.com trusty/restricted amd64 Packages             
Ign http://dl.google.com stable/main Translation-fr                            
Ign http://dl.google.com stable/main Translation-en                            
Atteint http://archive.ubuntu.com trusty/universe amd64 Packages               
Atteint http://archive.ubuntu.com trusty/multiverse amd64 Packages             
Atteint http://extra.linuxmint.com rebecca/main i386 Packages                  
Atteint http://packages.linuxmint.com rebecca/upstream amd64 Packages          
Atteint http://archive.ubuntu.com trusty/main i386 Packages                    
Atteint http://archive.ubuntu.com trusty/restricted i386 Packages              
Atteint http://archive.ubuntu.com trusty/universe i386 Packages                
Atteint http://archive.ubuntu.com trusty/multiverse i386 Packages              
Atteint http://packages.linuxmint.com rebecca/import amd64 Packages            
Atteint http://archive.ubuntu.com trusty/main Translation-fr                   
Atteint http://archive.ubuntu.com trusty/main Translation-en                   
Atteint http://archive.ubuntu.com trusty/multiverse Translation-fr             
Atteint http://archive.ubuntu.com trusty/multiverse Translation-en             
Atteint http://packages.linuxmint.com rebecca/main i386 Packages               
Atteint http://archive.ubuntu.com trusty/restricted Translation-fr             
Atteint http://archive.ubuntu.com trusty/restricted Translation-en             
Ign https://deb.nodesource.com trusty/main Translation-fr_FR                   
Ign https://deb.nodesource.com trusty/main Translation-fr                      
Atteint http://archive.ubuntu.com trusty/universe Translation-fr               
Atteint http://archive.ubuntu.com trusty/universe Translation-en               
Ign https://deb.nodesource.com trusty/main Translation-en                      
Atteint http://packages.linuxmint.com rebecca/upstream i386 Packages           
Atteint http://packages.linuxmint.com rebecca/import i386 Packages             
Ign http://archive.ubuntu.com trusty/main Translation-fr_FR                    
Ign http://archive.ubuntu.com trusty/multiverse Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/restricted Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/universe Translation-fr_FR                
Ign http://extra.linuxmint.com rebecca/main Translation-fr_FR                  
Ign http://extra.linuxmint.com rebecca/main Translation-fr                     
Ign http://extra.linuxmint.com rebecca/main Translation-en                     
Ign http://repo.steampowered.com precise/steam Translation-fr_FR        
Ign http://repo.steampowered.com precise/steam Translation-fr                  
Ign http://repo.steampowered.com precise/steam Translation-en                  
Ign http://packages.linuxmint.com rebecca/import Translation-fr_FR             
Ign http://packages.linuxmint.com rebecca/import Translation-fr                
Ign http://packages.linuxmint.com rebecca/import Translation-en                
Ign http://packages.linuxmint.com rebecca/main Translation-fr_FR               
Ign http://packages.linuxmint.com rebecca/main Translation-fr                  
Ign http://packages.linuxmint.com rebecca/main Translation-en                  
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr_FR           
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr              
Ign http://packages.linuxmint.com rebecca/upstream Translation-en              
Lecture des listes de paquets... Fait                                          

## You seem to be using Linux Mint version rebecca.
## This maps to Ubuntu "trusty"... Adjusting for you...

## Confirming "trusty" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/trusty/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v4.x LTS Argon repo...

+ echo 'deb https://deb.nodesource.com/node_4.x trusty main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_4.x trusty main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Ign http://dl.google.com stable InRelease
Atteint http://repo.steampowered.com precise InRelease                         
Ign http://archive.ubuntu.com trusty InRelease                                 
Atteint http://ppa.launchpad.net trusty InRelease                              
Atteint http://security.ubuntu.com trusty-security InRelease                   
Ign http://archive.canonical.com trusty InRelease                              
Atteint http://repo.steampowered.com precise/steam Sources                     
Atteint http://dl.google.com stable Release.gpg                                
Atteint http://archive.ubuntu.com trusty-updates InRelease                     
Atteint http://archive.canonical.com trusty Release.gpg                        
Atteint http://ppa.launchpad.net trusty/main Sources                           
Atteint http://security.ubuntu.com trusty-security/main amd64 Packages         
Atteint http://archive.canonical.com trusty Release                            
Atteint http://archive.ubuntu.com trusty Release.gpg                           
Atteint http://dl.google.com stable Release                                    
Atteint http://ppa.launchpad.net trusty/main amd64 Packages                    
Atteint http://repo.steampowered.com precise/steam amd64 Packages              
Atteint http://security.ubuntu.com trusty-security/restricted amd64 Packages   
Atteint http://archive.ubuntu.com trusty-updates/main amd64 Packages           
Atteint http://archive.canonical.com trusty/partner amd64 Packages             
Atteint http://ppa.launchpad.net trusty/main i386 Packages                     
Atteint http://dl.google.com stable/main amd64 Packages                        
Ign http://packages.linuxmint.com rebecca InRelease                            
Ign http://extra.linuxmint.com rebecca InRelease                               
Atteint http://ppa.launchpad.net trusty/main Translation-en                    
Atteint http://security.ubuntu.com trusty-security/universe amd64 Packages     
Atteint http://archive.ubuntu.com trusty-updates/restricted amd64 Packages     
Atteint http://archive.canonical.com trusty/partner i386 Packages              
Atteint http://repo.steampowered.com precise/steam i386 Packages               
Atteint https://deb.nodesource.com trusty InRelease                            
Atteint http://archive.ubuntu.com trusty-updates/universe amd64 Packages       
Atteint http://security.ubuntu.com trusty-security/multiverse amd64 Packages   
Atteint http://archive.canonical.com trusty/partner Translation-en             
Atteint http://packages.linuxmint.com rebecca Release.gpg                      
Atteint http://extra.linuxmint.com rebecca Release.gpg                         
Atteint https://deb.nodesource.com trusty/main Sources                         
Atteint http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages     
Atteint http://security.ubuntu.com trusty-security/main i386 Packages          
Atteint https://deb.nodesource.com trusty/main amd64 Packages                  
Atteint http://archive.ubuntu.com trusty-updates/main i386 Packages            
Atteint http://security.ubuntu.com trusty-security/restricted i386 Packages    
Atteint https://deb.nodesource.com trusty/main i386 Packages                   
Atteint http://archive.ubuntu.com trusty-updates/restricted i386 Packages      
Atteint http://security.ubuntu.com trusty-security/universe i386 Packages      
Réception de : 1 https://deb.nodesource.com trusty/main Translation-fr_FR      
Atteint http://archive.ubuntu.com trusty-updates/universe i386 Packages        
Atteint http://security.ubuntu.com trusty-security/multiverse i386 Packages    
Atteint http://security.ubuntu.com trusty-security/main Translation-en         
Atteint http://archive.ubuntu.com trusty-updates/multiverse i386 Packages      
Atteint http://packages.linuxmint.com rebecca Release                          
Atteint http://extra.linuxmint.com rebecca Release                             
Atteint http://security.ubuntu.com trusty-security/multiverse Translation-en   
Atteint http://archive.ubuntu.com trusty-updates/main Translation-en           
Atteint http://security.ubuntu.com trusty-security/restricted Translation-en   
Atteint http://archive.ubuntu.com trusty-updates/multiverse Translation-en     
Atteint http://security.ubuntu.com trusty-security/universe Translation-en     
Atteint http://archive.ubuntu.com trusty-updates/restricted Translation-en     
Atteint http://archive.ubuntu.com trusty-updates/universe Translation-en       
Atteint http://packages.linuxmint.com rebecca/main amd64 Packages              
Atteint http://extra.linuxmint.com rebecca/main amd64 Packages                 
Atteint http://archive.ubuntu.com trusty Release                               
Ign http://dl.google.com stable/main Translation-fr_FR                         
Atteint http://archive.ubuntu.com trusty/main amd64 Packages                   
Ign http://dl.google.com stable/main Translation-fr                            
Atteint http://archive.ubuntu.com trusty/restricted amd64 Packages             
Ign http://dl.google.com stable/main Translation-en                            
Ign https://deb.nodesource.com trusty/main Translation-fr_FR                   
Atteint http://archive.ubuntu.com trusty/universe amd64 Packages               
Atteint http://packages.linuxmint.com rebecca/upstream amd64 Packages          
Atteint http://extra.linuxmint.com rebecca/main i386 Packages                  
Ign https://deb.nodesource.com trusty/main Translation-fr                      
Atteint http://archive.ubuntu.com trusty/multiverse amd64 Packages             
Ign https://deb.nodesource.com trusty/main Translation-en                      
Atteint http://archive.ubuntu.com trusty/main i386 Packages                    
Atteint http://archive.ubuntu.com trusty/restricted i386 Packages              
Atteint http://archive.ubuntu.com trusty/universe i386 Packages                
Atteint http://archive.ubuntu.com trusty/multiverse i386 Packages              
Atteint http://packages.linuxmint.com rebecca/import amd64 Packages            
Atteint http://archive.ubuntu.com trusty/main Translation-fr                   
Atteint http://archive.ubuntu.com trusty/main Translation-en                   
Atteint http://packages.linuxmint.com rebecca/main i386 Packages               
Atteint http://archive.ubuntu.com trusty/multiverse Translation-fr             
Atteint http://archive.ubuntu.com trusty/multiverse Translation-en             
Atteint http://archive.ubuntu.com trusty/restricted Translation-fr             
Atteint http://archive.ubuntu.com trusty/restricted Translation-en             
Atteint http://packages.linuxmint.com rebecca/upstream i386 Packages           
Atteint http://archive.ubuntu.com trusty/universe Translation-fr               
Atteint http://archive.ubuntu.com trusty/universe Translation-en               
Atteint http://packages.linuxmint.com rebecca/import i386 Packages             
Ign http://archive.ubuntu.com trusty/main Translation-fr_FR                    
Ign http://archive.ubuntu.com trusty/multiverse Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/restricted Translation-fr_FR              
Ign http://archive.ubuntu.com trusty/universe Translation-fr_FR                
Ign http://extra.linuxmint.com rebecca/main Translation-fr_FR                  
Ign http://extra.linuxmint.com rebecca/main Translation-fr                     
Ign http://extra.linuxmint.com rebecca/main Translation-en                     
Ign http://repo.steampowered.com precise/steam Translation-fr_FR               
Ign http://repo.steampowered.com precise/steam Translation-fr                  
Ign http://repo.steampowered.com precise/steam Translation-en                  
Ign http://packages.linuxmint.com rebecca/import Translation-fr_FR             
Ign http://packages.linuxmint.com rebecca/import Translation-fr                
Ign http://packages.linuxmint.com rebecca/import Translation-en                
Ign http://packages.linuxmint.com rebecca/main Translation-fr_FR               
Ign http://packages.linuxmint.com rebecca/main Translation-fr                  
Ign http://packages.linuxmint.com rebecca/main Translation-en                  
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr_FR           
Ign http://packages.linuxmint.com rebecca/upstream Translation-fr              
Ign http://packages.linuxmint.com rebecca/upstream Translation-en              
Lecture des listes de paquets... Fait                                          

## Run `apt-get install nodejs` (as root) to install Node.js v4.x LTS Argon and npm

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
nodejs est déjà la plus récente version disponible.
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  ax25-node gyp libax25 libc-ares-dev libc-ares2 libjs-node-uuid libssl-dev
  libv8-3.14-dev libv8-3.14.5 node-abbrev node-ansi node-archy node-async
  node-block-stream node-combined-stream node-cookie-jar node-delayed-stream
  node-forever-agent node-form-data node-fstream node-fstream-ignore
  node-github-url-from-git node-glob node-graceful-fs node-gyp node-inherits
  node-ini node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs
  node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-which openbsd-inetd zlib1g-dev
Veuillez utiliser « apt-get autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 771 non mis à jour.
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.3.0
updated 1 package in 8.982s
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
+ bower@1.8.0
updated 1 package in 3.807s
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
+ gulp@3.9.1
updated 1 package in 7.5s
Installation des dépendances php avec Composer...
./install-debian.sh: ligne 80: composer : commande introuvable
Installation des dépendances js avec nodejs et bower
up to date in 3.107s
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/arsleust/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.readFileSync (fs.js:540:33)
    at Configstore.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
Ajout de dev-upont.enpc.fr au fichier hosts
127.0.0.1 dev-upont.enpc.fr

```

**Comment by PhilippeFerreiraDeSousa** [comment]
Ton apt il est bizarre normalement il n'y a pas besoin d'indiquer la version et apt t'installes la dernière. Fait :
`sudo -E apt-get install -y php7.0-cli php7.0-fpm php7.0-curl php7.0-gd php7.0-imap php7.0-intl php7.0-mcrypt php7.0-mysql`

**Comment by PhilippeFerreiraDeSousa** [comment]
Fait `sudo usermod -a -G www-data $(whoami)`

**Comment by PhilippeFerreiraDeSousa** [comment]
echo -e "\e[1m\e[34mCréation d'une base de données...\e[0m"
echo "CREATE DATABASE upont" | mysql -u root -p

sudo cp utils/install/www.conf-debian /etc/php/7.0/fpm/pool.d/www.conf-debian
sudo mkdir /etc/php/7.0/conf.d
sudo cp utils/install/global.ini /etc/php/7.0/conf.d/global.ini

sudo cp utils/install/php-fpm.conf /etc/nginx/conf.d/php-fpm.conf
sudo service php-fpm restart

echo -e "\e[1m\e[34mInstallation de Composer...\e[0m"

mkdir ~/.composer/cache
chmod -R 0777 ~/.composer/cache

echo -e "\e[1m\e[34mInstallation de Phpdoc...\e[0m"

curl -sL http://www.phpdoc.org/phpDocumentor.phar
sudo mv phpDocumentor.phar /usr/local/bin/phpdoc

echo -e "\e[1m\e[34mInstallation des dépendances php avec Composer...\e[0m"

cd back
composer install
`

**Comment by PhilippeFerreiraDeSousa** [comment]
Il reste nginx, il y a une erreur 
> nginx: unrecognized service

mais pas d'erreur d'installation de nginx, `nginx -v` te donne quoi ?
