### ISSUE TITLE
Impossible d'ajouter les fixtures

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont#285]
```
~/projects/upont >>> sudo docker-compose exec upont-back bin/console doc:fix:load -n    ±[●][master-dev]

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
Did you forget a "use" statement for another namespace? in /app/src/Kernel.php:32
Stack trace:
#0 /app/vendor/symfony/http-kernel/Kernel.php(494): App\Kernel->registerBundles()
#1 /app/vendor/symfony/http-kernel/Kernel.php(134): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /app/vendor/symfony/framework-bundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /app/vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/bin/console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /app/src/Kernel.php on line 32

```
@LouisTrezzini  ?

**Comment by PhilippeFerreiraDeSousa** [comment]
This is not an issue related to uPont
